
import harirayavirtualhouse.Strategic.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alang
 */
public class MainHouse extends javax.swing.JFrame {

    /**
     * Creates new form MainHouse
     */
    public MainHouse() {
        

        initComponents();
        
        Crackle.setVisible(false);
        Crackle1.setVisible(false); 
        Crackle2.setVisible(false);
        
         Crown.setVisible(false);
        Crown1.setVisible(false); 
        Crown2.setVisible(false);
        
        Fish.setVisible(false);
        Fish1.setVisible(false); 
        Fish2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Crackle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Crackle1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Crackle2 = new javax.swing.JLabel();
        Crown = new javax.swing.JLabel();
        Crown1 = new javax.swing.JLabel();
        Crown2 = new javax.swing.JLabel();
        Fish = new javax.swing.JLabel();
        Fish1 = new javax.swing.JLabel();
        Fish2 = new javax.swing.JLabel();
        backgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Fire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        Crackle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crackle.JPG"))); // NOI18N
        Crackle.setDisabledIcon(null);
        getContentPane().add(Crackle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crown", "Crackle", "Fish", "All", "None", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        Crackle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crackle.JPG"))); // NOI18N
        getContentPane().add(Crackle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 50));

        jLabel3.setText("Choose Firework");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 110, -1));

        Crackle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crackle.JPG"))); // NOI18N
        getContentPane().add(Crackle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 50, 50));

        Crown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crown.JPG"))); // NOI18N
        getContentPane().add(Crown, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 50));

        Crown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crown.JPG"))); // NOI18N
        getContentPane().add(Crown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        Crown2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crown.JPG"))); // NOI18N
        getContentPane().add(Crown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 50));

        Fish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fish.JPG"))); // NOI18N
        getContentPane().add(Fish, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 40, 40));

        Fish1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fish.JPG"))); // NOI18N
        getContentPane().add(Fish1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 50, 40));

        Fish2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fish.JPG"))); // NOI18N
        getContentPane().add(Fish2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 50, 50));

        backgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hariraya.jpg"))); // NOI18N
        backgroundimage.setText("jLabel1");
        getContentPane().add(backgroundimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              String selectedfirework=jComboBox1.getSelectedItem().toString();
        
        if(selectedfirework.equals("Crackle")){
            CrackleFirework crackle=new CrackleFirework();
            crackle.setBehavior(new Fly());
            crackle.performFire();
            JOptionPane.showMessageDialog(null, crackle.performFire());
            
            crackle.setBehavior(new Sparkle());
            crackle.performFire();
            JOptionPane.showMessageDialog(null, crackle.performFire());
            
            Crackle.setVisible(true);
            Crackle1.setVisible(true); 
            Crackle2.setVisible(true);
              
         Crown.setVisible(false);
        Crown1.setVisible(false); 
        Crown2.setVisible(false);
        
        Fish.setVisible(false);
        Fish1.setVisible(false); 
        Fish2.setVisible(false);
            
        } else if(selectedfirework.equals("Fish")){
            Fish.setVisible(true);
            Fish1.setVisible(true); 
            Fish2.setVisible(true);
            
            
            FishFirework fish=new FishFirework();
            fish.setBehavior(new Fly());
            fish.performFire();
            JOptionPane.showMessageDialog(null, fish.performFire());
            fish.setBehavior(new Sparkle());
            fish.performFire();
            JOptionPane.showMessageDialog(null, fish.performFire());
            fish.setBehavior(new Trail());
            fish.performFire();
            JOptionPane.showMessageDialog(null, fish.performFire());
            
             
            
            
             Crackle.setVisible(false);
        Crackle1.setVisible(false); 
        Crackle2.setVisible(false);
        
         Crown.setVisible(false);
        Crown1.setVisible(false); 
        Crown2.setVisible(false);
        
  
            
        } else if(selectedfirework.equals("Crown")){
            CrownFirework crown=new CrownFirework();
            crown.setBehavior(new Fly());
            crown.performFire();
            JOptionPane.showMessageDialog(null, crown.performFire());
            crown.setBehavior(new Sparkle());
            crown.performFire();
            JOptionPane.showMessageDialog(null, crown.performFire());
            
            Crown.setVisible(true);
            Crown1.setVisible(true); 
            Crown2.setVisible(true);
            
             Crackle.setVisible(false);
        Crackle1.setVisible(false); 
        Crackle2.setVisible(false);
       
        
        Fish.setVisible(false);
        Fish1.setVisible(false); 
        Fish2.setVisible(false);
            
            
        } else if(selectedfirework.equals("All")) {
            String all;
            
            CrownFirework crown=new CrownFirework();
            crown.setBehavior(new Fly());
            crown.performFire();
            crown.setBehavior(new Sparkle());
            crown.performFire();
            
             FishFirework fish=new FishFirework();
            fish.setBehavior(new Fly());
            fish.performFire();
            fish.setBehavior(new Sparkle());
            fish.performFire();
            fish.setBehavior(new Trail());
            fish.performFire();
            
            
            
             CrackleFirework crackle=new CrackleFirework();
            crackle.setBehavior(new Fly());
            crackle.performFire();
            crackle.setBehavior(new Sparkle());
            crackle.performFire();
            
            
            JOptionPane.showMessageDialog(null, "Firewall fly, sparkle and leaves a trail");
            
            Crown.setVisible(true);
            Crown1.setVisible(true); 
            Crown2.setVisible(true);
            Fish.setVisible(true);
            Fish1.setVisible(true); 
            Fish2.setVisible(true);
             Crackle.setVisible(true);
            Crackle1.setVisible(true); 
            Crackle2.setVisible(true);
        } else if(selectedfirework.equals("None")) {
               Crackle.setVisible(false);
        Crackle1.setVisible(false); 
        Crackle2.setVisible(false);
        
         Crown.setVisible(false);
        Crown1.setVisible(false); 
        Crown2.setVisible(false);
        
        Fish.setVisible(false);
        Fish1.setVisible(false); 
        Fish2.setVisible(false);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainHouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Crackle;
    private javax.swing.JLabel Crackle1;
    private javax.swing.JLabel Crackle2;
    private javax.swing.JLabel Crown;
    private javax.swing.JLabel Crown1;
    private javax.swing.JLabel Crown2;
    private javax.swing.JLabel Fish;
    private javax.swing.JLabel Fish1;
    private javax.swing.JLabel Fish2;
    private javax.swing.JLabel backgroundimage;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
